server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/d_learning"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: phuongthanh229
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2KB

---
upload-file:
  base-uri: file:///E:/Course/upload/


---
spring:
  messaging:
    stomp:
      brokerRelay:
        enabled: false



