server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/d_learning"
#    url: ${DBMS_CONNECTION:jdbc:mysql://mysql-course:3307/d_learning}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      password: ""  # Nếu không có mật khẩu


  mail:
    host: smtp.gmail.com
    port: 587
    username: duclkde170045@fpt.edu.vn
    password: liccjzpfvszbrssa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 70MB
      max-request-size: 70MB
      file-size-threshold: 2KB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 24
  refreshable-duration: 72

outbound:
  identity:
    client-id: "1063674841920-mtlapuiv2d8gc3rgf6b4oi4vlaa31pah.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

#  facebook:
#    client-id: "1184572409447891"
#    client-secret: "bcf09ccad760216ccae41807e1a82d1f"
#    redirect-uri: "http://localhost:8080/authenticate-fb"
#    grant-type: "authorization_code"

cloudinary:
  cloud-name: "dznef2sae"
  api-key: "537285485346489"
  api-secret: "PHu0HBagBqf1rgfKMSJpSLUh29M"

#logging:
#  level:
#    com.spring.dlearning.exception.GlobalExceptionHandler: OFF
#    com.spring.dlearning.exception.AppException: OFF



