server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/d_learning"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 70MB
      max-request-size: 70MB
      file-size-threshold: 2KB

---
upload-file:
  base-uri: file:///C:/D-Learning/upload/


